# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"1\n\x10GetClientRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"%\n\tGetClient\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\x11GetClientResponse\x12\x1d\n\tclientele\x18\x01 \x01(\x0b\x32\n.GetClient*<\n\x06\x43lient\x12\x0b\n\x07USER_ID\x10\x00\x12\x08\n\x04NAME\x10\x01\x12\x0b\n\x07SURNAME\x10\x02\x12\x0e\n\nID_ADDRESS\x10\x03*+\n\x07\x41\x64\x64ress\x12\n\n\x06STREET\x10\x00\x12\n\n\x06NUMBER\x10\x01\x12\x08\n\x04\x43ITY\x10\x02\x32=\n\tgetClient\x12\x30\n\x07\x43lients\x12\x11.GetClientRequest\x1a\x12.GetClientResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENT._serialized_start=156
  _CLIENT._serialized_end=216
  _ADDRESS._serialized_start=218
  _ADDRESS._serialized_end=261
  _GETCLIENTREQUEST._serialized_start=14
  _GETCLIENTREQUEST._serialized_end=63
  _GETCLIENT._serialized_start=65
  _GETCLIENT._serialized_end=102
  _GETCLIENTRESPONSE._serialized_start=104
  _GETCLIENTRESPONSE._serialized_end=154
  _GETCLIENT._serialized_start=263
  _GETCLIENT._serialized_end=324
# @@protoc_insertion_point(module_scope)
